feat: more robust error counting via trap

diff --git a/bin/lint b/bin/lint
--- a/bin/lint
+++ b/bin/lint
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 # Description:
 #   Lint all-the-things.
@@ -6,14 +6,14 @@
 set -o errexit
 set -o nounset
 
-ensure_dependency() {
+function ensure_dependency() {
 	command -v "${1}" >/dev/null 2>&1 || {
 		echo >&2 "Please install ${1} before using this script. Exiting..."
 		return 1
 	}
 }
 
-ensure_dependencies() {
+function ensure_dependencies() {
 	ensure_dependency checkmake
 	ensure_dependency hadolint
 	ensure_dependency markdownlint
@@ -22,54 +22,47 @@ ensure_dependencies() {
 	ensure_dependency shfmt
 }
 
-find_files() {
+function find_files() {
 	find . -type f -not -path '*/\.git/*' "$@"
 }
 
-find_other_shellscripts() {
+function find_other_shellscripts() {
 	find_files -not -name '*.sh' | xargs -r file --mime-type | grep -oP '[^:]+(?=:\s+text/x-shellscript)'
 }
 
-lint() {
+function lint() {
 	# Keep track of exit statuses, to either succeed or fail as a whole:
-	set +e
-	status=0
+	set +o errexit
+	failures=0
+	trap 'failures=$((failures+1))' ERR
 
 	find_files -name 'Makefile' | xargs -r checkmake
-	status=$((status + $?))
-
 	find_files -name 'Dockerfile' | xargs -r hadolint
-	status=$((status + $?))
-
 	find_files -name '*.md' | xargs -r markdownlint
-	status=$((status + $?))
-
 	find_files | xargs -r misspell
-	status=$((status + $?))
 
 	for f in $(find_files -name '*.sh'); do
 		shellcheck "${f}"
-		status=$((status + $?))
 		shfmt -d "${f}"
-		status=$((status + $?))
 		shexec "${f}"
-		status=$((status + $?))
 	done
 
 	for f in $(find_other_shellscripts); do
 		shellcheck "${f}"
-		status=$((status + $?))
 		shfmt -d "${f}"
-		status=$((status + $?))
 		shexec "${f}"
-		status=$((status + $?))
 	done
 
-	set -e
-	return $status
+	set -o errexit
+	if ((failures == 0)); then
+		return 0
+	else
+		echo >&2 "${failures} failures."
+		return 1
+	fi
 }
 
-main() {
+function main() {
 	ensure_dependencies
 	lint
 }
